# version: '3.8'

services:
  # Backend service (Python FastAPI)
  backend:
    image: sales-dashboard-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sales-dashboard-backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sales-dashboard-network

  # Frontend service (Next.js)
  frontend:
    image: sales-dashboard-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sales-dashboard-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000

    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - sales-dashboard-network

# Define network
networks:
  sales-dashboard-network:
    driver: bridge

# Define volumes for data persistence
volumes:
  backend_data:
  frontend_data:
